-- Canonical admin data structures and transaction boundaries.
-- This migration intentionally does not review any existing pending suggestion.

create table if not exists public.dish_catalog (
  id bigint generated by default as identity primary key,
  campus_id text not null default 'bjfu' references public.campuses(id) on update cascade,
  name text not null,
  location text not null,
  status text not null default 'published',
  search_text text generated always as (lower(coalesce(name, '') || ' ' || coalesce(location, ''))) stored,
  rating_average numeric(2, 1) not null default 0,
  rating_count integer not null default 0,
  rating_1_count integer not null default 0,
  rating_2_count integer not null default 0,
  rating_3_count integer not null default 0,
  rating_4_count integer not null default 0,
  rating_5_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dish_catalog_name_not_blank check (nullif(btrim(name), '') is not null),
  constraint dish_catalog_location_not_blank check (nullif(btrim(location), '') is not null),
  constraint dish_catalog_status_check check (status in ('published', 'hidden'))
);

create table if not exists public.dish_ratings (
  dish_id bigint not null references public.dish_catalog(id) on delete cascade on update cascade,
  user_id uuid not null references public.profiles(id) on delete cascade on update cascade,
  stars integer not null check (stars between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (dish_id, user_id)
);

alter table public.catalog_suggestions
  add column if not exists initial_stars integer,
  add column if not exists approved_dish_id bigint references public.dish_catalog(id) on delete set null on update cascade;

alter table public.catalog_suggestions drop constraint if exists catalog_suggestions_type_check;
alter table public.catalog_suggestions add constraint catalog_suggestions_type_check
  check (suggestion_type in ('teacher', 'course', 'dish'));
alter table public.catalog_suggestions drop constraint if exists catalog_suggestions_initial_stars_check;
alter table public.catalog_suggestions add constraint catalog_suggestions_initial_stars_check
  check (initial_stars is null or initial_stars between 1 and 5);
alter table public.catalog_suggestions drop constraint if exists catalog_suggestions_review_shape;
alter table public.catalog_suggestions add constraint catalog_suggestions_review_shape check (
  (status = 'open'
    and approved_teacher_id is null and approved_course_id is null and approved_dish_id is null
    and reviewed_by is null and reviewed_at is null)
  or (status = 'rejected'
    and approved_teacher_id is null and approved_course_id is null and approved_dish_id is null
    and reviewed_at is not null)
  or (status = 'approved' and reviewed_at is not null and (
    (suggestion_type = 'teacher' and approved_teacher_id is not null and approved_course_id is null and approved_dish_id is null)
    or (suggestion_type = 'course' and approved_teacher_id is null and approved_course_id is not null and approved_dish_id is null)
    or (suggestion_type = 'dish' and approved_teacher_id is null and approved_course_id is null and approved_dish_id is not null)
  ))
) not valid;

drop index if exists public.idx_catalog_suggestions_open_unique;
create unique index idx_catalog_suggestions_open_unique
on public.catalog_suggestions (
  campus_id,
  suggestion_type,
  lower(btrim(name)),
  lower(btrim(unit)),
  lower(btrim(coalesce(teacher_name, ''))),
  lower(btrim(coalesce(category, '')))
)
where status = 'open';

drop index if exists public.dish_catalog_name_location_unique;
create unique index if not exists idx_dish_catalog_campus_name_location_unique
on public.dish_catalog (campus_id, lower(btrim(name)), lower(btrim(location)));
create index if not exists idx_dish_catalog_rating on public.dish_catalog (rating_average desc, rating_count desc, id asc);
create index if not exists idx_dish_catalog_search_text on public.dish_catalog (search_text);
create index if not exists idx_dish_catalog_location on public.dish_catalog
(campus_id, location, status, rating_average desc, rating_count desc);
create index if not exists idx_dish_catalog_admin_search_trgm on public.dish_catalog
using gin (search_text extensions.gin_trgm_ops);
create index if not exists idx_dish_catalog_campus_id on public.dish_catalog (campus_id);
create index if not exists idx_dish_ratings_user_id on public.dish_ratings (user_id);

drop trigger if exists dish_catalog_set_updated_at on public.dish_catalog;
create trigger dish_catalog_set_updated_at before update on public.dish_catalog
for each row execute function public.set_updated_at();
drop trigger if exists dish_ratings_set_updated_at on public.dish_ratings;
create trigger dish_ratings_set_updated_at before update on public.dish_ratings
for each row execute function public.set_updated_at();

create or replace function public.refresh_dish_rating_summary(target_dish_id bigint)
returns void language sql security definer set search_path = public, pg_temp as $$
  update public.dish_catalog set
    rating_average = coalesce((select round(avg(stars)::numeric, 1) from public.dish_ratings where dish_id = target_dish_id), 0),
    rating_count = (select count(*)::integer from public.dish_ratings where dish_id = target_dish_id),
    rating_1_count = (select count(*)::integer from public.dish_ratings where dish_id = target_dish_id and stars = 1),
    rating_2_count = (select count(*)::integer from public.dish_ratings where dish_id = target_dish_id and stars = 2),
    rating_3_count = (select count(*)::integer from public.dish_ratings where dish_id = target_dish_id and stars = 3),
    rating_4_count = (select count(*)::integer from public.dish_ratings where dish_id = target_dish_id and stars = 4),
    rating_5_count = (select count(*)::integer from public.dish_ratings where dish_id = target_dish_id and stars = 5)
  where id = target_dish_id;
$$;

create or replace function public.handle_dish_rating_summary_sync()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if tg_op = 'DELETE' then
    perform public.refresh_dish_rating_summary(old.dish_id);
    return old;
  end if;
  if tg_op = 'UPDATE' and old.dish_id <> new.dish_id then
    perform public.refresh_dish_rating_summary(old.dish_id);
  end if;
  perform public.refresh_dish_rating_summary(new.dish_id);
  return new;
end;
$$;

drop trigger if exists dish_ratings_sync_summary on public.dish_ratings;
create trigger dish_ratings_sync_summary after insert or update or delete on public.dish_ratings
for each row execute function public.handle_dish_rating_summary_sync();

alter table public.dish_catalog enable row level security;
alter table public.dish_ratings enable row level security;
drop policy if exists "catalog_suggestions_insert_authenticated" on public.catalog_suggestions;
create policy "catalog_suggestions_insert_authenticated" on public.catalog_suggestions for insert to authenticated
with check (
  status = 'open' and campus_id = public.current_profile_campus_id()
  and approved_teacher_id is null and approved_course_id is null and approved_dish_id is null
  and admin_note is null and reviewed_by is null and reviewed_at is null
  and (user_id is null or public.can_use_profile(user_id))
);
drop policy if exists "dish_catalog_select_published_authenticated" on public.dish_catalog;
create policy "dish_catalog_select_published_authenticated" on public.dish_catalog for select to authenticated
using (status = 'published' and campus_id = public.current_profile_campus_id());
drop policy if exists "dish_ratings_select_self" on public.dish_ratings;
create policy "dish_ratings_select_self" on public.dish_ratings for select to authenticated
using (public.can_use_profile(user_id) and exists (
  select 1 from public.dish_catalog where id = dish_ratings.dish_id and campus_id = public.current_profile_campus_id()
));
drop policy if exists "dish_ratings_insert_self" on public.dish_ratings;
create policy "dish_ratings_insert_self" on public.dish_ratings for insert to authenticated
with check (public.can_use_profile(user_id) and exists (
  select 1 from public.dish_catalog where id = dish_ratings.dish_id
    and campus_id = public.current_profile_campus_id() and status = 'published'
));
drop policy if exists "dish_ratings_update_self" on public.dish_ratings;
create policy "dish_ratings_update_self" on public.dish_ratings for update to authenticated
using (public.can_use_profile(user_id) and exists (
  select 1 from public.dish_catalog where id = dish_ratings.dish_id
    and campus_id = public.current_profile_campus_id()
)) with check (public.can_use_profile(user_id) and exists (
  select 1 from public.dish_catalog where id = dish_ratings.dish_id
    and campus_id = public.current_profile_campus_id()
));

revoke all privileges on table public.dish_catalog, public.dish_ratings from public, anon, authenticated, service_role;
grant select on table public.dish_catalog to authenticated;
grant select, insert, update on table public.dish_ratings to authenticated;
grant select, insert, update, delete on table public.dish_catalog, public.dish_ratings to service_role;
revoke all privileges on sequence public.dish_catalog_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.dish_catalog_id_seq to service_role;

create or replace function public.admin_approve_catalog_suggestion_v1(
  p_suggestion_id uuid,
  p_admin_id uuid,
  p_admin_note text default null
)
returns public.catalog_suggestions
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  suggestion public.catalog_suggestions%rowtype;
  target_teacher_id bigint;
  target_course_id bigint;
  target_dish_id bigint;
begin
  select * into suggestion from public.catalog_suggestions
  where id = p_suggestion_id for update;
  if suggestion.id is null then raise exception 'ADMIN_CATALOG_SUGGESTION_NOT_FOUND' using errcode = 'P0001'; end if;
  if suggestion.status <> 'open' then raise exception 'ADMIN_CATALOG_SUGGESTION_ALREADY_REVIEWED' using errcode = 'P0001'; end if;
  if nullif(btrim(suggestion.campus_id), '') is null then raise exception 'ADMIN_CAMPUS_REQUIRED' using errcode = '22023'; end if;
  if suggestion.user_id is not null and not exists (
    select 1 from public.profiles where id = suggestion.user_id
      and community_campus_id = suggestion.campus_id and community_access_status = 'approved'
  ) then
    raise exception 'ADMIN_CATALOG_SUGGESTION_CAMPUS_MISMATCH' using errcode = 'P0001';
  end if;

  if suggestion.suggestion_type = 'teacher' then
    select id into target_teacher_id from public.teachers
    where campus_id = suggestion.campus_id and lower(btrim(name)) = lower(btrim(suggestion.name))
      and lower(btrim(unit)) = lower(btrim(suggestion.unit))
    order by id limit 1 for update;
    if target_teacher_id is null then
      insert into public.teachers(campus_id, name, unit, status)
      values (suggestion.campus_id, btrim(suggestion.name), btrim(suggestion.unit), 'published')
      on conflict do nothing returning id into target_teacher_id;
      if target_teacher_id is null then
        select id into target_teacher_id from public.teachers
        where campus_id = suggestion.campus_id and lower(btrim(name)) = lower(btrim(suggestion.name))
          and lower(btrim(unit)) = lower(btrim(suggestion.unit)) order by id limit 1 for update;
      end if;
    end if;
    update public.teachers set status = 'published' where id = target_teacher_id and status <> 'published';
    if suggestion.initial_stars is not null and suggestion.user_id is not null then
      insert into public.teacher_ratings(teacher_id, user_id, stars)
      values (target_teacher_id, suggestion.user_id, suggestion.initial_stars)
      on conflict (teacher_id, user_id) do update set stars = excluded.stars;
    end if;
  elsif suggestion.suggestion_type = 'course' then
    select id into target_course_id from public.course_catalog
    where campus_id = suggestion.campus_id and lower(btrim(name)) = lower(btrim(suggestion.name))
      and lower(btrim(unit)) = lower(btrim(suggestion.unit))
      and lower(btrim(category)) = lower(btrim(coalesce(suggestion.category, '公选课')))
    order by id limit 1 for update;
    if target_course_id is null then
      insert into public.course_catalog(campus_id, name, unit, category, credit, status)
      values (suggestion.campus_id, btrim(suggestion.name), btrim(suggestion.unit),
        coalesce(nullif(btrim(suggestion.category), ''), '公选课'), coalesce(suggestion.credit, 0), 'published')
      on conflict do nothing returning id into target_course_id;
      if target_course_id is null then
        select id into target_course_id from public.course_catalog
        where campus_id = suggestion.campus_id and lower(btrim(name)) = lower(btrim(suggestion.name))
          and lower(btrim(unit)) = lower(btrim(suggestion.unit))
          and lower(btrim(category)) = lower(btrim(coalesce(suggestion.category, '公选课')))
        order by id limit 1 for update;
      end if;
    end if;
    update public.course_catalog set status = 'published', credit = coalesce(suggestion.credit, credit)
    where id = target_course_id and (status <> 'published' or suggestion.credit is not null);
    if suggestion.initial_stars is not null and suggestion.user_id is not null then
      insert into public.course_ratings(course_id, user_id, stars)
      values (target_course_id, suggestion.user_id, suggestion.initial_stars)
      on conflict (course_id, user_id) do update set stars = excluded.stars;
    end if;
  elsif suggestion.suggestion_type = 'dish' then
    select id into target_dish_id from public.dish_catalog
    where campus_id = suggestion.campus_id and lower(btrim(name)) = lower(btrim(suggestion.name))
      and lower(btrim(location)) = lower(btrim(suggestion.unit))
    order by id limit 1 for update;
    if target_dish_id is null then
      insert into public.dish_catalog(campus_id, name, location, status)
      values (suggestion.campus_id, btrim(suggestion.name), btrim(suggestion.unit), 'published')
      on conflict do nothing returning id into target_dish_id;
      if target_dish_id is null then
        select id into target_dish_id from public.dish_catalog
        where campus_id = suggestion.campus_id and lower(btrim(name)) = lower(btrim(suggestion.name))
          and lower(btrim(location)) = lower(btrim(suggestion.unit)) order by id limit 1 for update;
      end if;
    end if;
    update public.dish_catalog set status = 'published' where id = target_dish_id and status <> 'published';
    if suggestion.initial_stars is not null and suggestion.user_id is not null then
      insert into public.dish_ratings(dish_id, user_id, stars)
      values (target_dish_id, suggestion.user_id, suggestion.initial_stars)
      on conflict (dish_id, user_id) do update set stars = excluded.stars;
    end if;
  else
    raise exception 'ADMIN_INVALID_CATALOG_SUGGESTION_TYPE' using errcode = '22023';
  end if;

  update public.catalog_suggestions set
    status = 'approved', approved_teacher_id = target_teacher_id,
    approved_course_id = target_course_id, approved_dish_id = target_dish_id,
    admin_note = nullif(btrim(coalesce(p_admin_note, '')), ''),
    reviewed_by = p_admin_id, reviewed_at = now()
  where id = suggestion.id returning * into suggestion;
  return suggestion;
end;
$$;

create or replace function public.admin_approve_postgraduate_suggestion_v1(
  p_suggestion_id uuid,
  p_admin_id uuid,
  p_summary text default null,
  p_admin_note text default null
)
returns public.postgraduate_source_suggestions
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  suggestion public.postgraduate_source_suggestions%rowtype;
  source_id uuid;
begin
  select * into suggestion from public.postgraduate_source_suggestions
  where id = p_suggestion_id for update;
  if suggestion.id is null then raise exception 'ADMIN_POSTGRADUATE_SUGGESTION_NOT_FOUND' using errcode = 'P0001'; end if;
  if suggestion.status <> 'open' then raise exception 'ADMIN_POSTGRADUATE_SUGGESTION_ALREADY_REVIEWED' using errcode = 'P0001'; end if;
  insert into public.postgraduate_sources(
    title, summary, source_url, source_kind, trust_level, school, unit, major,
    exam_year, status, verified_at, created_by, updated_by
  ) values (
    suggestion.title, coalesce(p_summary, suggestion.note, ''), suggestion.source_url,
    suggestion.source_kind, 'verified_user', suggestion.school, suggestion.unit,
    suggestion.major, suggestion.exam_year, 'published', now(), p_admin_id, p_admin_id
  ) returning id into source_id;
  update public.postgraduate_source_suggestions set
    status = 'approved', approved_source_id = source_id,
    admin_note = nullif(btrim(coalesce(p_admin_note, '')), ''),
    reviewed_by = p_admin_id, reviewed_at = now()
  where id = suggestion.id returning * into suggestion;
  return suggestion;
end;
$$;

create or replace function public.admin_approve_campus_request_v1(
  p_request_id uuid,
  p_admin_id uuid,
  p_campus_id text default null,
  p_display_name text default null,
  p_short_name text default null,
  p_new_campus_id text default null,
  p_admin_note text default null
)
returns public.campus_membership_requests
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  request_row public.campus_membership_requests%rowtype;
  target_campus_id text;
  target_display_name text;
  normalized_name text;
begin
  select * into request_row from public.campus_membership_requests
  where id = p_request_id for update;
  if request_row.id is null then raise exception 'COMMUNITY_REQUEST_NOT_FOUND' using errcode = 'P0001'; end if;
  if request_row.status <> 'pending' then raise exception 'ADMIN_CAMPUS_REQUEST_ALREADY_REVIEWED' using errcode = 'P0001'; end if;

  if request_row.request_type = 'school_change' then
    target_campus_id := request_row.requested_campus_id;
  elsif nullif(lower(btrim(coalesce(p_campus_id, ''))), '') is not null
    and lower(btrim(p_campus_id)) <> 'new' then
    target_campus_id := lower(btrim(p_campus_id));
  else
    target_display_name := coalesce(nullif(btrim(p_display_name), ''), request_row.school_name);
    normalized_name := public.normalize_school_name(target_display_name);
    if normalized_name in (public.normalize_school_name('北京林业大学'), public.normalize_school_name('北林')) then
      raise exception 'ADMIN_INVALID_CAMPUS_TARGET' using errcode = '22023';
    end if;
    select id into target_campus_id from public.campuses where normalized_name = public.normalize_school_name(target_display_name);
    if target_campus_id is null then
      target_campus_id := lower(btrim(coalesce(nullif(p_new_campus_id, ''), 'campus-' || replace(request_row.id::text, '-', ''))));
      insert into public.campuses(id, display_name, short_name, connector_kind, status, normalized_name, is_community_enabled, is_system)
      values (target_campus_id, target_display_name, coalesce(nullif(btrim(p_short_name), ''), left(target_display_name, 6)),
        'custom', 'active', normalized_name, true, false);
    end if;
  end if;
  if target_campus_id is null or target_campus_id = 'general'
    or (request_row.request_type <> 'school_change' and target_campus_id = 'bjfu') then
    raise exception 'ADMIN_INVALID_CAMPUS_TARGET' using errcode = '22023';
  end if;
  if not exists (select 1 from public.campuses where id = target_campus_id and status = 'active' and is_community_enabled) then
    raise exception 'COMMUNITY_CAMPUS_NOT_FOUND' using errcode = 'P0001';
  end if;
  return public.approve_campus_membership_request(request_row.id, target_campus_id, p_admin_id, p_admin_note);
end;
$$;

create or replace function public.admin_pin_post_v1(
  p_post_id uuid,
  p_scope text,
  p_category text,
  p_priority integer,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_reason text,
  p_admin_id uuid
)
returns public.community_post_pins
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  post_row public.posts%rowtype;
  pin_row public.community_post_pins%rowtype;
begin
  select * into post_row from public.posts where id = p_post_id for update;
  if post_row.id is null then raise exception 'ADMIN_POST_NOT_FOUND' using errcode = 'P0001'; end if;
  if post_row.status <> 'published' then raise exception 'ADMIN_POST_NOT_PUBLISHED' using errcode = 'P0001'; end if;
  update public.community_post_pins set status = 'inactive'
  where post_id = p_post_id and scope = p_scope
    and coalesce(category, '') = coalesce(p_category, '') and status = 'active';
  insert into public.community_post_pins(post_id, campus_id, scope, category, priority, starts_at, ends_at, status, reason, created_by)
  values (p_post_id, post_row.campus_id, p_scope, p_category, p_priority, p_starts_at, p_ends_at, 'active', p_reason, p_admin_id)
  returning * into pin_row;
  return pin_row;
end;
$$;

create or replace function public.admin_moderate_posts_v1(
  p_post_ids uuid[],
  p_status text,
  p_reason text,
  p_admin_id uuid
)
returns setof public.posts
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if p_status not in ('published', 'hidden') then raise exception 'ADMIN_INVALID_POST_STATUS' using errcode = '22023'; end if;
  if cardinality(p_post_ids) = 1 then
    if not exists (select 1 from public.posts where id = p_post_ids[1]) then
      raise exception 'ADMIN_POST_NOT_FOUND' using errcode = 'P0001';
    end if;
    if exists (select 1 from public.posts where id = p_post_ids[1] and status = 'deleted') then
      raise exception 'ADMIN_POST_DELETED' using errcode = 'P0001';
    end if;
  end if;
  if p_status = 'hidden' then
    update public.community_post_pins set status = 'inactive'
    where post_id = any(p_post_ids) and status = 'active';
  end if;
  return query update public.posts set
    status = p_status, moderated_by = p_admin_id, moderated_at = now(),
    moderation_reason = case when p_status = 'hidden' then coalesce(nullif(btrim(p_reason), ''), 'Hidden by admin') else null end
  where id = any(p_post_ids) and status <> 'deleted'
  returning *;
end;
$$;

create or replace function public.admin_resolve_moderation_report_v1(
  p_report_id uuid,
  p_status text,
  p_resolution_note text,
  p_hide_content boolean,
  p_mute_user boolean,
  p_muted_until timestamptz,
  p_muted_reason text,
  p_admin_id uuid
)
returns public.community_reports
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  report_row public.community_reports%rowtype;
begin
  select * into report_row from public.community_reports where id = p_report_id for update;
  if report_row.id is null then raise exception 'ADMIN_REPORT_NOT_FOUND' using errcode = 'P0001'; end if;
  if report_row.status not in ('open', 'reviewed') then raise exception 'ADMIN_REPORT_ALREADY_REVIEWED' using errcode = 'P0001'; end if;
  if p_status not in ('reviewed', 'resolved', 'rejected') then raise exception 'ADMIN_INVALID_REPORT_STATUS' using errcode = '22023'; end if;
  if p_hide_content then
    if report_row.target_type = 'post' and report_row.post_id is not null then
      update public.community_post_pins set status = 'inactive' where post_id = report_row.post_id and status = 'active';
      update public.posts set status = 'hidden', moderated_by = p_admin_id, moderated_at = now(), moderation_reason = p_resolution_note
      where id = report_row.post_id and status <> 'deleted';
    elsif report_row.target_type = 'comment' and report_row.comment_id is not null then
      update public.comments set status = 'hidden', moderated_by = p_admin_id, moderated_at = now(), moderation_reason = p_resolution_note
      where id = report_row.comment_id and status <> 'deleted';
    end if;
  end if;
  if p_mute_user and report_row.reported_user_id is not null then
    update public.profiles set muted_until = coalesce(p_muted_until, now() + interval '1 year'),
      muted_reason = coalesce(nullif(btrim(p_muted_reason), ''), 'Community report upheld'),
      muted_by = p_admin_id, muted_at = now()
    where id = report_row.reported_user_id;
  end if;
  update public.community_reports set status = p_status, resolved_by = p_admin_id,
    resolved_at = now(), resolution_note = p_resolution_note
  where id = report_row.id returning * into report_row;
  return report_row;
end;
$$;

create or replace function public.admin_revoke_sessions_on_account_security_change()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if old.active is distinct from new.active
    or old.role is distinct from new.role
    or old.password_hash is distinct from new.password_hash then
    update public.admin_sessions set revoked_at = coalesce(revoked_at, now())
    where admin_id = new.id and revoked_at is null;
  end if;
  return new;
end;
$$;
drop trigger if exists admin_accounts_revoke_sessions_on_security_change on public.admin_accounts;
create trigger admin_accounts_revoke_sessions_on_security_change
after update of active, role, password_hash on public.admin_accounts
for each row execute function public.admin_revoke_sessions_on_account_security_change();

update public.community_post_pins pins
set status = 'inactive'
from public.posts posts
where pins.post_id = posts.id and pins.status = 'active' and posts.status <> 'published';

revoke all on function public.admin_approve_catalog_suggestion_v1(uuid, uuid, text) from public, anon, authenticated;
revoke all on function public.admin_approve_postgraduate_suggestion_v1(uuid, uuid, text, text) from public, anon, authenticated;
revoke all on function public.admin_approve_campus_request_v1(uuid, uuid, text, text, text, text, text) from public, anon, authenticated;
revoke all on function public.admin_pin_post_v1(uuid, text, text, integer, timestamptz, timestamptz, text, uuid) from public, anon, authenticated;
revoke all on function public.admin_moderate_posts_v1(uuid[], text, text, uuid) from public, anon, authenticated;
revoke all on function public.admin_resolve_moderation_report_v1(uuid, text, text, boolean, boolean, timestamptz, text, uuid) from public, anon, authenticated;
revoke all on function public.admin_revoke_sessions_on_account_security_change() from public, anon, authenticated;
revoke all on function public.refresh_dish_rating_summary(bigint) from public, anon, authenticated, service_role;
revoke all on function public.handle_dish_rating_summary_sync() from public, anon, authenticated, service_role;
grant execute on function public.admin_approve_catalog_suggestion_v1(uuid, uuid, text) to service_role;
grant execute on function public.admin_approve_postgraduate_suggestion_v1(uuid, uuid, text, text) to service_role;
grant execute on function public.admin_approve_campus_request_v1(uuid, uuid, text, text, text, text, text) to service_role;
grant execute on function public.admin_pin_post_v1(uuid, text, text, integer, timestamptz, timestamptz, text, uuid) to service_role;
grant execute on function public.admin_moderate_posts_v1(uuid[], text, text, uuid) to service_role;
grant execute on function public.admin_resolve_moderation_report_v1(uuid, text, text, boolean, boolean, timestamptz, text, uuid) to service_role;
grant execute on function public.refresh_dish_rating_summary(bigint) to service_role;
grant execute on function public.handle_dish_rating_summary_sync() to service_role;

select pg_notify('pgrst', 'reload schema');
