create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  name text not null,
  unit text not null,
  search_text text generated always as (
    lower(coalesce(name, '') || ' ' || coalesce(unit, ''))
  ) stored,
  rating_average numeric(2, 1) not null default 0,
  rating_count integer not null default 0,
  rating_1_count integer not null default 0,
  rating_2_count integer not null default 0,
  rating_3_count integer not null default 0,
  rating_4_count integer not null default 0,
  rating_5_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint teachers_name_unit_unique unique (name, unit),
  constraint teachers_name_not_blank check (nullif(btrim(name), '') is not null),
  constraint teachers_unit_not_blank check (nullif(btrim(unit), '') is not null)
);

create table if not exists public.teacher_ratings (
  teacher_id bigint not null references public.teachers (id) on delete cascade on update cascade,
  user_id uuid not null references public.profiles (id) on delete cascade on update cascade,
  stars integer not null check (stars between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (teacher_id, user_id)
);

create index if not exists idx_teachers_rating
on public.teachers (rating_average desc, rating_count desc, id asc);

create index if not exists idx_teachers_search_text
on public.teachers (search_text);

create index if not exists idx_teacher_ratings_user_id
on public.teacher_ratings (user_id);

drop trigger if exists teachers_set_updated_at on public.teachers;
create trigger teachers_set_updated_at
before update on public.teachers
for each row
execute function public.set_updated_at();

drop trigger if exists teacher_ratings_set_updated_at on public.teacher_ratings;
create trigger teacher_ratings_set_updated_at
before update on public.teacher_ratings
for each row
execute function public.set_updated_at();

create or replace function public.refresh_teacher_rating_summary(target_teacher_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update public.teachers
  set
    rating_average = coalesce((
      select round(avg(stars)::numeric, 1)
      from public.teacher_ratings
      where teacher_id = target_teacher_id
    ), 0),
    rating_count = (
      select count(*)::integer
      from public.teacher_ratings
      where teacher_id = target_teacher_id
    ),
    rating_1_count = (
      select count(*)::integer
      from public.teacher_ratings
      where teacher_id = target_teacher_id and stars = 1
    ),
    rating_2_count = (
      select count(*)::integer
      from public.teacher_ratings
      where teacher_id = target_teacher_id and stars = 2
    ),
    rating_3_count = (
      select count(*)::integer
      from public.teacher_ratings
      where teacher_id = target_teacher_id and stars = 3
    ),
    rating_4_count = (
      select count(*)::integer
      from public.teacher_ratings
      where teacher_id = target_teacher_id and stars = 4
    ),
    rating_5_count = (
      select count(*)::integer
      from public.teacher_ratings
      where teacher_id = target_teacher_id and stars = 5
    )
  where id = target_teacher_id;
$$;

create or replace function public.handle_teacher_rating_summary_sync()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    perform public.refresh_teacher_rating_summary(old.teacher_id);
    return old;
  end if;

  if tg_op = 'UPDATE' and old.teacher_id <> new.teacher_id then
    perform public.refresh_teacher_rating_summary(old.teacher_id);
  end if;

  perform public.refresh_teacher_rating_summary(new.teacher_id);
  return new;
end;
$$;

drop trigger if exists teacher_ratings_sync_summary on public.teacher_ratings;
create trigger teacher_ratings_sync_summary
after insert or update or delete on public.teacher_ratings
for each row
execute function public.handle_teacher_rating_summary_sync();

alter table public.teachers enable row level security;
alter table public.teacher_ratings enable row level security;

drop policy if exists "teachers_select_authenticated" on public.teachers;
create policy "teachers_select_authenticated"
on public.teachers
for select
to authenticated
using (true);

drop policy if exists "teacher_ratings_select_self" on public.teacher_ratings;
create policy "teacher_ratings_select_self"
on public.teacher_ratings
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "teacher_ratings_insert_self" on public.teacher_ratings;
create policy "teacher_ratings_insert_self"
on public.teacher_ratings
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "teacher_ratings_update_self" on public.teacher_ratings;
create policy "teacher_ratings_update_self"
on public.teacher_ratings
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

select pg_notify('pgrst', 'reload schema');
