create table if not exists public.course_catalog (
  id bigint generated by default as identity primary key,
  name text not null,
  unit text not null,
  category text not null default '公选课',
  credit numeric(4, 1) not null default 0,
  status text not null default 'published',
  search_text text generated always as (
    lower(
      coalesce(name, '') || ' ' ||
      coalesce(unit, '') || ' ' ||
      coalesce(category, '')
    )
  ) stored,
  rating_average numeric(2, 1) not null default 0,
  rating_count integer not null default 0,
  rating_1_count integer not null default 0,
  rating_2_count integer not null default 0,
  rating_3_count integer not null default 0,
  rating_4_count integer not null default 0,
  rating_5_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint course_catalog_name_unit_category_unique unique (name, unit, category),
  constraint course_catalog_name_not_blank check (nullif(btrim(name), '') is not null),
  constraint course_catalog_unit_not_blank check (nullif(btrim(unit), '') is not null),
  constraint course_catalog_category_not_blank check (nullif(btrim(category), '') is not null),
  constraint course_catalog_credit_valid check (credit >= 0),
  constraint course_catalog_status_check check (status in ('published', 'hidden'))
);

create table if not exists public.course_ratings (
  course_id bigint not null references public.course_catalog (id) on delete cascade on update cascade,
  user_id uuid not null references public.profiles (id) on delete cascade on update cascade,
  stars integer not null check (stars between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (course_id, user_id)
);

create index if not exists idx_course_catalog_rating
on public.course_catalog (rating_average desc, rating_count desc, id asc);

create index if not exists idx_course_catalog_search_text
on public.course_catalog (search_text);

create index if not exists idx_course_catalog_category
on public.course_catalog (category, status, rating_average desc, rating_count desc);

create index if not exists idx_course_ratings_user_id
on public.course_ratings (user_id);

drop trigger if exists course_catalog_set_updated_at on public.course_catalog;
create trigger course_catalog_set_updated_at
before update on public.course_catalog
for each row
execute function public.set_updated_at();

drop trigger if exists course_ratings_set_updated_at on public.course_ratings;
create trigger course_ratings_set_updated_at
before update on public.course_ratings
for each row
execute function public.set_updated_at();

create or replace function public.refresh_course_rating_summary(target_course_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update public.course_catalog
  set
    rating_average = coalesce((
      select round(avg(stars)::numeric, 1)
      from public.course_ratings
      where course_id = target_course_id
    ), 0),
    rating_count = (
      select count(*)::integer
      from public.course_ratings
      where course_id = target_course_id
    ),
    rating_1_count = (
      select count(*)::integer
      from public.course_ratings
      where course_id = target_course_id and stars = 1
    ),
    rating_2_count = (
      select count(*)::integer
      from public.course_ratings
      where course_id = target_course_id and stars = 2
    ),
    rating_3_count = (
      select count(*)::integer
      from public.course_ratings
      where course_id = target_course_id and stars = 3
    ),
    rating_4_count = (
      select count(*)::integer
      from public.course_ratings
      where course_id = target_course_id and stars = 4
    ),
    rating_5_count = (
      select count(*)::integer
      from public.course_ratings
      where course_id = target_course_id and stars = 5
    )
  where id = target_course_id;
$$;

create or replace function public.handle_course_rating_summary_sync()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    perform public.refresh_course_rating_summary(old.course_id);
    return old;
  end if;

  if tg_op = 'UPDATE' and old.course_id <> new.course_id then
    perform public.refresh_course_rating_summary(old.course_id);
  end if;

  perform public.refresh_course_rating_summary(new.course_id);
  return new;
end;
$$;

drop trigger if exists course_ratings_sync_summary on public.course_ratings;
create trigger course_ratings_sync_summary
after insert or update or delete on public.course_ratings
for each row
execute function public.handle_course_rating_summary_sync();

alter table public.course_catalog enable row level security;
alter table public.course_ratings enable row level security;

drop policy if exists "course_catalog_select_published_authenticated" on public.course_catalog;
create policy "course_catalog_select_published_authenticated"
on public.course_catalog
for select
to authenticated
using (status = 'published');

drop policy if exists "course_ratings_select_self" on public.course_ratings;
create policy "course_ratings_select_self"
on public.course_ratings
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "course_ratings_insert_self" on public.course_ratings;
create policy "course_ratings_insert_self"
on public.course_ratings
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "course_ratings_update_self" on public.course_ratings;
create policy "course_ratings_update_self"
on public.course_ratings
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

revoke all privileges on table
  public.course_catalog,
  public.course_ratings
from public, anon, authenticated, service_role;

grant select on table
  public.course_catalog
to authenticated;

grant select, insert, update on table
  public.course_ratings
to authenticated;

grant select, insert, update, delete on table
  public.course_catalog,
  public.course_ratings
to service_role;

revoke all privileges on sequence
  public.course_catalog_id_seq
from public, anon, authenticated, service_role;

grant usage, select on sequence
  public.course_catalog_id_seq
to service_role;

revoke execute on function
  public.refresh_course_rating_summary(bigint),
  public.handle_course_rating_summary_sync()
from public, anon, authenticated, service_role;

grant execute on function
  public.refresh_course_rating_summary(bigint),
  public.handle_course_rating_summary_sync()
to service_role;

select pg_notify('pgrst', 'reload schema');
