create table if not exists public.dish_catalog (
  id bigint generated by default as identity primary key,
  name text not null,
  location text not null,
  status text not null default 'published',
  search_text text generated always as (
    lower(
      coalesce(name, '') || ' ' ||
      coalesce(location, '')
    )
  ) stored,
  rating_average numeric(2, 1) not null default 0,
  rating_count integer not null default 0,
  rating_1_count integer not null default 0,
  rating_2_count integer not null default 0,
  rating_3_count integer not null default 0,
  rating_4_count integer not null default 0,
  rating_5_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint dish_catalog_name_location_unique unique (name, location),
  constraint dish_catalog_name_not_blank check (nullif(btrim(name), '') is not null),
  constraint dish_catalog_location_not_blank check (nullif(btrim(location), '') is not null),
  constraint dish_catalog_status_check check (status in ('published', 'hidden'))
);

create table if not exists public.dish_ratings (
  dish_id bigint not null references public.dish_catalog (id) on delete cascade on update cascade,
  user_id uuid not null references public.profiles (id) on delete cascade on update cascade,
  stars integer not null check (stars between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (dish_id, user_id)
);

create index if not exists idx_dish_catalog_rating
on public.dish_catalog (rating_average desc, rating_count desc, id asc);

create index if not exists idx_dish_catalog_search_text
on public.dish_catalog (search_text);

create index if not exists idx_dish_catalog_location
on public.dish_catalog (location, status, rating_average desc, rating_count desc);

create index if not exists idx_dish_ratings_user_id
on public.dish_ratings (user_id);

drop trigger if exists dish_catalog_set_updated_at on public.dish_catalog;
create trigger dish_catalog_set_updated_at
before update on public.dish_catalog
for each row
execute function public.set_updated_at();

drop trigger if exists dish_ratings_set_updated_at on public.dish_ratings;
create trigger dish_ratings_set_updated_at
before update on public.dish_ratings
for each row
execute function public.set_updated_at();

create or replace function public.refresh_dish_rating_summary(target_dish_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update public.dish_catalog
  set
    rating_average = coalesce((
      select round(avg(stars)::numeric, 1)
      from public.dish_ratings
      where dish_id = target_dish_id
    ), 0),
    rating_count = (
      select count(*)::integer
      from public.dish_ratings
      where dish_id = target_dish_id
    ),
    rating_1_count = (
      select count(*)::integer
      from public.dish_ratings
      where dish_id = target_dish_id and stars = 1
    ),
    rating_2_count = (
      select count(*)::integer
      from public.dish_ratings
      where dish_id = target_dish_id and stars = 2
    ),
    rating_3_count = (
      select count(*)::integer
      from public.dish_ratings
      where dish_id = target_dish_id and stars = 3
    ),
    rating_4_count = (
      select count(*)::integer
      from public.dish_ratings
      where dish_id = target_dish_id and stars = 4
    ),
    rating_5_count = (
      select count(*)::integer
      from public.dish_ratings
      where dish_id = target_dish_id and stars = 5
    )
  where id = target_dish_id;
$$;

create or replace function public.handle_dish_rating_summary_sync()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    perform public.refresh_dish_rating_summary(old.dish_id);
    return old;
  end if;

  if tg_op = 'UPDATE' and old.dish_id <> new.dish_id then
    perform public.refresh_dish_rating_summary(old.dish_id);
  end if;

  perform public.refresh_dish_rating_summary(new.dish_id);
  return new;
end;
$$;

drop trigger if exists dish_ratings_sync_summary on public.dish_ratings;
create trigger dish_ratings_sync_summary
after insert or update or delete on public.dish_ratings
for each row
execute function public.handle_dish_rating_summary_sync();

alter table public.catalog_suggestions
  add column if not exists initial_stars integer,
  add column if not exists approved_dish_id bigint references public.dish_catalog (id) on delete set null on update cascade;

alter table public.catalog_suggestions
  drop constraint if exists catalog_suggestions_type_check;

alter table public.catalog_suggestions
  add constraint catalog_suggestions_type_check
  check (suggestion_type in ('teacher', 'course', 'dish'));

alter table public.catalog_suggestions
  drop constraint if exists catalog_suggestions_initial_stars_check;

alter table public.catalog_suggestions
  add constraint catalog_suggestions_initial_stars_check
  check (initial_stars is null or initial_stars between 1 and 5);

drop index if exists public.idx_catalog_suggestions_open_unique;
drop index if exists public.idx_catalog_suggestions_search_text;

alter table public.catalog_suggestions
  drop column if exists search_text;

alter table public.catalog_suggestions
  add column search_text text generated always as (
    lower(
      coalesce(name, '') || ' ' ||
      coalesce(unit, '') || ' ' ||
      coalesce(teacher_name, '') || ' ' ||
      coalesce(category, '') || ' ' ||
      coalesce(note, '')
    )
  ) stored;

create index if not exists idx_catalog_suggestions_search_text
on public.catalog_suggestions (search_text);

create unique index if not exists idx_catalog_suggestions_open_unique
on public.catalog_suggestions (
  suggestion_type,
  lower(btrim(name)),
  lower(btrim(unit)),
  lower(btrim(coalesce(teacher_name, ''))),
  lower(btrim(coalesce(category, '')))
)
where status = 'open';

alter table public.dish_catalog enable row level security;
alter table public.dish_ratings enable row level security;

drop policy if exists "dish_catalog_select_published_authenticated" on public.dish_catalog;
create policy "dish_catalog_select_published_authenticated"
on public.dish_catalog
for select
to authenticated
using (status = 'published');

drop policy if exists "dish_ratings_select_self" on public.dish_ratings;
create policy "dish_ratings_select_self"
on public.dish_ratings
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "dish_ratings_insert_self" on public.dish_ratings;
create policy "dish_ratings_insert_self"
on public.dish_ratings
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "dish_ratings_update_self" on public.dish_ratings;
create policy "dish_ratings_update_self"
on public.dish_ratings
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

revoke all privileges on table
  public.dish_catalog,
  public.dish_ratings
from public, anon, authenticated, service_role;

grant select on table
  public.dish_catalog
to authenticated;

grant select, insert, update on table
  public.dish_ratings
to authenticated;

grant select, insert, update, delete on table
  public.dish_catalog,
  public.dish_ratings
to service_role;

revoke all privileges on sequence
  public.dish_catalog_id_seq
from public, anon, authenticated, service_role;

grant usage, select on sequence
  public.dish_catalog_id_seq
to service_role;

grant insert on table
  public.catalog_suggestions
to authenticated;

grant select, insert, update, delete on table
  public.catalog_suggestions
to service_role;

revoke execute on function
  public.refresh_dish_rating_summary(bigint),
  public.handle_dish_rating_summary_sync()
from public, anon, authenticated, service_role;

grant execute on function
  public.refresh_dish_rating_summary(bigint),
  public.handle_dish_rating_summary_sync()
to service_role;

select pg_notify('pgrst', 'reload schema');
